· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Installing into conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
· Running 2 total benchmarks (1 commits * 1 environments * 2 benchmarks)
[  0.00%] · For pangeo-storage-benchmarks commit hash c0a51679:
[  0.00%] ·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[  0.00%] ·· Benchmarking conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[ 50.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_benchmarks.time_read                                    ok
[ 50.00%] ···· 
               ========= ============= =========== ======== ======== ======== ======== ========
               --                                                    run_num                   
               ----------------------------------- --------------------------------------------
                backend   z_chunksize   n_workers     1        2        3        4        5    
               ========= ============= =========== ======== ======== ======== ======== ========
                  FUSE         5            60      2.08m    1.93m    1.91m    2.06m    2.08m  
                  FUSE         5            80      1.55m    1.46m    1.34m    1.28m    1.34m  
                  FUSE         5           100      1.11m    1.06m    1.20m    1.05m    1.10m  
                  FUSE         5           120      55.73s   52.72s   51.19s   51.95s   52.98s 
                  FUSE         5           140      50.73s   48.36s   44.23s   45.38s   44.58s 
                  FUSE         5           160      45.36s   43.53s   40.39s   44.26s   44.56s 
                  FUSE         10           60      50.20s   50.92s   51.81s   50.82s   56.14s 
                  FUSE         10           80      40.88s   41.22s   41.44s   44.26s   44.73s 
                  FUSE         10          100      37.30s   34.86s   59.11s   53.42s   35.45s 
                  FUSE         10          120      33.33s   33.49s   32.34s   32.05s   31.96s 
                  FUSE         10          140      28.65s   30.29s   34.92s   31.06s   29.70s 
                  FUSE         10          160      37.65s   25.42s   26.53s   27.54s   24.99s 
               ========= ============= =========== ======== ======== ======== ======== ========

[ 50.00%] ····· 
                
                For parameters: 'FUSE', 5, 60, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 60, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 60, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 60, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 60, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 80, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 80, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 80, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 80, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 80, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 100, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 100, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 100, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 100, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 100, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 120, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 120, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 120, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 120, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 120, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 140, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 140, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 140, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 140, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 140, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 160, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 160, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 160, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 160, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 5, 160, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 60, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 60, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 60, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 60, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 60, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 80, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 80, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 80, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 80, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 80, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 100, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 100, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 100, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 100, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 100, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 120, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 120, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 120, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 120, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 120, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 140, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 140, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 140, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 140, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 140, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 160, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 160, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 160, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 160, 4
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                
                For parameters: 'FUSE', 10, 160, 5
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)

[100.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes                 110524.67555236816
[100.00%] ····· /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                return f(*args, **kwds)

{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 110524.67555236816, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 110524.67555236816, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
results/storage-benchmarks-results.csv
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Installing into conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarrTraceback (most recent call last):
  File "run_benchmarks.py", line 284, in <module>
    main()
  File "run_benchmarks.py", line 272, in main
    call(['asv', 'run', '-e', '-b', args.benchmark[0]])
  File "/opt/conda/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Installing into conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
· Running 2 total benchmarks (1 commits * 1 environments * 2 benchmarks)
[  0.00%] · For pangeo-storage-benchmarks commit hash c0a51679:
[  0.00%] ·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[  0.00%] ·· Benchmarking conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[ 50.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_benchmarks.time_read                                failed
[ 50.00%] ···· 
               ========= ============== ============== ==============
               --             z_chunksize / n_workers / run_num      
               --------- --------------------------------------------
                backend   90 / 100 / 1   90 / 100 / 2   90 / 100 / 3 
               ========= ============== ============== ==============
                  FUSE       failed         failed         failed    
               ========= ============== ============== ==============

[ 50.00%] ····· 
                
                For parameters: 'FUSE', 90, 100, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                Traceback (most recent call last):
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                    commands[mode](args)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 772, in main_run
                    result = benchmark.do_run()
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 456, in do_run
                    return self.run(*self._current_params)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 548, in run
                    all_runs.extend(timer.repeat(repeat, number))
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 206, in repeat
                    t = self.timeit(number)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 178, in timeit
                    timing = self.inner(it, self.timer)
                  File "<timeit-src>", line 6, in inner
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 512, in <lambda>
                    func = lambda: self.func(*param)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/benchmark_tools.py", line 41, in func_wrapper
                    func(*args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/gcp_kubernetes_read_netCDF.py", line 62, in time_read
                    self.ds_netcdf_theta.max().load(retries=RETRIES)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataarray.py", line 633, in load
                    ds = self._to_temp_dataset().load(**kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataset.py", line 491, in load
                    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/dask/base.py", line 402, in compute
                    results = schedule(dsk, keys, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 2159, in get
                    direct=direct)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1562, in gather
                    asynchronous=asynchronous)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 652, in sync
                    return sync(self.loop, func, *args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 275, in sync
                    six.reraise(*error[0])
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 260, in f
                    result[0] = yield make_coro()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
                    value = future.result()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
                    yielded = self.gen.throw(*exc_info)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1439, in _gather
                    traceback)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                distributed.scheduler.KilledWorker: ('open_dataset-e08ebe1fcf5a6e7602b762cfdc36a2e5Theta-27dedf0e704fc80148f7d3064b319b31', 'tcp://10.25.214.3:46574')
                
                For parameters: 'FUSE', 90, 100, 2
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                Traceback (most recent call last):
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                    commands[mode](args)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 772, in main_run
                    result = benchmark.do_run()
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 456, in do_run
                    return self.run(*self._current_params)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 548, in run
                    all_runs.extend(timer.repeat(repeat, number))
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 206, in repeat
                    t = self.timeit(number)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 178, in timeit
                    timing = self.inner(it, self.timer)
                  File "<timeit-src>", line 6, in inner
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 512, in <lambda>
                    func = lambda: self.func(*param)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/benchmark_tools.py", line 41, in func_wrapper
                    func(*args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/gcp_kubernetes_read_netCDF.py", line 62, in time_read
                    self.ds_netcdf_theta.max().load(retries=RETRIES)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataarray.py", line 633, in load
                    ds = self._to_temp_dataset().load(**kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataset.py", line 491, in load
                    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/dask/base.py", line 402, in compute
                    results = schedule(dsk, keys, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 2159, in get
                    direct=direct)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1562, in gather
                    asynchronous=asynchronous)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 652, in sync
                    return sync(self.loop, func, *args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 275, in sync
                    six.reraise(*error[0])
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 260, in f
                    result[0] = yield make_coro()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
                    value = future.result()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
                    yielded = self.gen.throw(*exc_info)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1439, in _gather
                    traceback)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                distributed.scheduler.KilledWorker: ("('open_dataset-concatenate-c31ee54a601f8f793bcbaec20a38e3b8', 379, 0, 0, 0)", 'tcp://10.25.197.7:35020')
                
                For parameters: 'FUSE', 90, 100, 3
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                Traceback (most recent call last):
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                    commands[mode](args)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 772, in main_run
                    result = benchmark.do_run()
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 456, in do_run
                    return self.run(*self._current_params)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 548, in run
                    all_runs.extend(timer.repeat(repeat, number))
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 206, in repeat
                    t = self.timeit(number)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 178, in timeit
                    timing = self.inner(it, self.timer)
                  File "<timeit-src>", line 6, in inner
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 512, in <lambda>
                    func = lambda: self.func(*param)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/benchmark_tools.py", line 41, in func_wrapper
                    func(*args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/gcp_kubernetes_read_netCDF.py", line 62, in time_read
                    self.ds_netcdf_theta.max().load(retries=RETRIES)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataarray.py", line 633, in load
                    ds = self._to_temp_dataset().load(**kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataset.py", line 491, in load
                    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/dask/base.py", line 402, in compute
                    results = schedule(dsk, keys, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 2159, in get
                    direct=direct)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1562, in gather
                    asynchronous=asynchronous)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 652, in sync
                    return sync(self.loop, func, *args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 275, in sync
                    six.reraise(*error[0])
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 260, in f
                    result[0] = yield make_coro()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
                    value = future.result()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
                    yielded = self.gen.throw(*exc_info)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1439, in _gather
                    traceback)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                distributed.scheduler.KilledWorker: ('open_dataset-5265ec0d737811f57936dfce235b97e9Theta-01fae930b10d3401e381a8447d54d893', 'tcp://10.25.239.9:43561')

[100.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes                             failed
[100.00%] ····· asv: benchmark timed out (timeout 1200s)
                

{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': None, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': None, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
results/storage-benchmarks-results.csv
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Installing into conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
· Running 2 total benchmarks (1 commits * 1 environments * 2 benchmarks)
[  0.00%] · For pangeo-storage-benchmarks commit hash c0a51679:
[  0.00%] ·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[  0.00%] ·· Benchmarking conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[ 50.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_benchmarks.time_read                                                                                  failed
[ 50.00%] ···· 
               ========= ==============
               --        z_chunksize / n_workers / run_num
               --------- --------------
                backend   90 / 100 / 1 
               ========= ==============
                  FUSE       failed    
               ========= ==============

[ 50.00%] ····· 
                
                For parameters: 'FUSE', 90, 100, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)
                Traceback (most recent call last):
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                    commands[mode](args)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 772, in main_run
                    result = benchmark.do_run()
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 456, in do_run
                    return self.run(*self._current_params)
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 548, in run
                    all_runs.extend(timer.repeat(repeat, number))
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 206, in repeat
                    t = self.timeit(number)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/timeit.py", line 178, in timeit
                    timing = self.inner(it, self.timer)
                  File "<timeit-src>", line 6, in inner
                  File "/home/jovyan/.local/lib/python3.6/site-packages/asv/benchmark.py", line 512, in <lambda>
                    func = lambda: self.func(*param)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/benchmark_tools.py", line 41, in func_wrapper
                    func(*args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/benchmarks/gcp_kubernetes_read_netCDF.py", line 62, in time_read
                    self.ds_netcdf_theta.max().load(retries=RETRIES)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataarray.py", line 633, in load
                    ds = self._to_temp_dataset().load(**kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/xarray/core/dataset.py", line 491, in load
                    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/dask/base.py", line 402, in compute
                    results = schedule(dsk, keys, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 2159, in get
                    direct=direct)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1562, in gather
                    asynchronous=asynchronous)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 652, in sync
                    return sync(self.loop, func, *args, **kwargs)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 275, in sync
                    six.reraise(*error[0])
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/utils.py", line 260, in f
                    result[0] = yield make_coro()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
                    value = future.result()
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
                    yielded = self.gen.throw(*exc_info)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/distributed/client.py", line 1439, in _gather
                    traceback)
                  File "/home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/site-packages/six.py", line 693, in reraise
                    raise value
                distributed.scheduler.KilledWorker: ('open_dataset-dfbb11345c66cdcb26e09d716a59eafdTheta-8163653f47e9952625ea6eeac6e8bb42', 'tcp://10.26.0.4:44913')

[100.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes                                                                   1111653.8307113647
[100.00%] ····· /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                return f(*args, **kwds)

{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 1111653.8307113647, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 1111653.8307113647, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
results/storage-benchmarks-results.csv
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
·· Installing into conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
· Running 2 total benchmarks (1 commits * 1 environments * 2 benchmarks)
[  0.00%] · For pangeo-storage-benchmarks commit hash c0a51679:
[  0.00%] ·· Building for conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[  0.00%] ·· Benchmarking conda-py3.6-dask-distributed-gcsfs-h5netcdf-h5py-lz4-netcdf4-numpy-pip+dask_kubernetes-pip+h5pyd-pyyaml-rasterio-xarray-zarr
[ 50.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_benchmarks.time_read                                                                                      ok
[ 50.00%] ···· 
               ========= ==============
               --        z_chunksize / n_workers / run_num
               --------- --------------
                backend   10 / 100 / 1 
               ========= ==============
                  FUSE       5.60m     
               ========= ==============

[ 50.00%] ····· 
                
                For parameters: 'FUSE', 10, 100, 1
                /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                  return f(*args, **kwds)

[100.00%] ··· Running gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes                                                                   1111653.8307113647
[100.00%] ····· /home/jovyan/dev/storage-benchmarks/.asv/env/4147cb8bacd14ebb1c15e8248dc80f49/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
                return f(*args, **kwds)

{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 1111653.8307113647, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
{'gcp_kubernetes_read_netCDF.llc4320_ds_size.track_megabytes': 1111653.8307113647, 'gcp_kubernetes_read_zarr.llc4320_ds_size.track_megabytes': 1111653.8307113647}
hola
gcp_kubernetes_read_netCDF.
hola
gcp_kubernetes_read_zarr.
results/storage-benchmarks-results.csv
